language: python
python:
  - "3.6"
cache: pip
install:
  - pip install boto3
script: skip
deploy:
  provider: lambda
  role: $AWS_LAMBDA_ROLE_ARN
  function_name: "ak-crawler-dev-lbd"
  region: "us-east-2"
  handler_name: "handler"
  runtime: "python3.6"
  on:
    branch: dev
  provider: lambda
  role: $AWS_LAMBDA_ROLE_ARN
  function_name: "ak-crawler-prod-lbd"
  region: "us-east-2"
  handler_name: "handler"
  runtime: "python3.6"
  on:
    branch: prod
    
